### ISSUE TITLE
Support Azure Notification Hub templates

### ISSUE THREAD

**Issue by phongcao** [CatalystCode/react-native-azurenotificationhub#102]
Azure Notification Hub templates should be supported so that client applications can specify the exact format of the notifications they wants to receive:

https://docs.microsoft.com/en-us/azure/notification-hubs/notification-hubs-templates-cross-platform-push-messages

**Comment by kreativ-software** [comment]
Hi, any idea when this is testable?

**Comment by phongcao** [comment]
I've planned to add this feature in the next version, which will be released within 1 - 2 weeks from now.

**Comment by kreativ-software** [comment]
Ah cool! If you have a specific branch to test we're more than happy to test it for you.

**Comment by kreativ-software** [comment]
Hi! Any idea when this is testable?

**Comment by phongcao** [comment]
@kreativ-software Implementation for Android has been done on [this branch](https://github.com/CatalystCode/react-native-azurenotificationhub/tree/phongcao/mixer-improvements):

iOS will be completed in a couple days.

**Comment by kreativ-software** [comment]
Nice! Will test tomorrow or the day after

**Comment by kreativ-software** [comment]
I was checking the android.md. Is it possible to register multiple templates with some time between? aka not all at once?

**Comment by phongcao** [comment]
I'm not sure about that. Can you just invoke `registerTemplate` multiple times?
