### ISSUE TITLE
twice before the first has returned (IOS)

### ISSUE THREAD

**Issue by yasaricli** [CatalystCode/react-native-azurenotificationhub#116]
I get an error when I try to get permission as follows.

<img width="356" alt="Screen Shot 2020-03-15 at 22 33 47" src="https://user-images.githubusercontent.com/1306620/76709133-2f0f7780-670d-11ea-842d-460959843c7d.png">

```JS
NotificationHubIos.requestPermissions();
```
error:

    Cannot call requestPermissions twice before the first has returned.

It only happens when ios and 2nd run

Thanks.

**Comment by phongcao** [comment]
@yasaricli Can you let me know why you need to call `requestPermissions` method twice? Is it because the first run didn't succeed or you want to request different permissions in the second run?

**Comment by yasaricli** [comment]
When I run "**requestPermissions**" every time in version `0.9.0` it doesn't give an error.

Here's an example of how I run it.

```JS
import React, { Component } from 'react';
import NotificationHubIos from 'react-native-azurenotificationhub/index.ios';

import Index extends Component {
  componentDidMount() {

    // Maybe an permission check can be done here?
  
    NotificationHubIos.requestPermissions();
  }

  render() {
    return (
      ...
    )
  }
}
```

thanks.

**Comment by yasaricli** [comment]
I'm waiting for this bug. When can you do it @phongcao 

Thanks.

**Comment by phongcao** [comment]
I plan to have a look at this issue in a couple days and it should be resolved with the next release.

**Comment by phongcao** [comment]
@yasaricli Should be fixed on master branch.

**Comment by yasaricli** [comment]
thanks @phongcao

**Comment by yasaricli** [comment]
this error continues. 

I updated it in v0.9.5 version, it gives error.

**Comment by phongcao** [comment]
@yasaricli That's strange. I just did some testing again and this issue doesn't seem to occur. Please provide more details/error logs/screenshots if you still see it.

**Comment by phongcao** [comment]
Make sure you update your `App.js` as well since there is a lot of changes in 095.

**Comment by yasaricli** [comment]
there is no problem at first start. But then **ctrl + r**, or refresh, gets an error.

![Screen Shot 2020-03-26 at 19 54 16](https://user-images.githubusercontent.com/1306620/77682178-8fbd7080-6fa7-11ea-9850-6bf4b9c63284.png)


<img width="352" alt="Screen Shot 2020-03-26 at 21 17 45" src="https://user-images.githubusercontent.com/1306620/77682169-892ef900-6fa7-11ea-8458-49b76247b0ff.png">

**Comment by potatoengineer** [comment]
I have this issue as well. Is there a solution? @yasaricli @phongcao 

I am currently on `"^0.9.5-Patched.1"` and using it like such 
```
              <Button
                buttonStyle={styles.button}
                title="Enable Notifications"
                onPress={async () => {
                  await iosNotifications.getInstance().register(true);
                  await dismiss();
                }}
              />
 ```
