### ISSUE TITLE
Building issue related to manifest merger failed

### ISSUE THREAD

**Issue by phongcao** [CatalystCode/react-native-azurenotificationhub#13]
This issue is related to the azure-mobile-services sdk. The [android icon tag](https://github.com/Azure/azure-mobile-services/blob/master/sdk/android/src/notifications-handler/src/main/AndroidManifest.xml) in the manifest file is creating conflict when react-native generates the default template project. The readme file should be updated to warn developers about it.

**Comment by kcfgl** [comment]
@phongcao Sorry for the naive question, but how do I resolve this?  Thx.
