### ISSUE TITLE
Cannot set channel description

### ISSUE THREAD

**Issue by lauming1111** [CatalystCode/react-native-azurenotificationhub#134]
Is there a option call channelDescription to replace "rn-push-notification-channel-description"?
Seem only have channelName now.

**Comment by lauming1111** [comment]
or just disable it

**Comment by phongcao** [comment]
@lauming1111 Right now it's not supported but I can add it when I have time this weekend. May I ask why you want to disable it?

**Comment by lauming1111** [comment]
Thanks,
Because I think it is an optional function now.

**Comment by lauming1111** [comment]
thank you for the update.

is there a parameter that can handle badge numbers in the main theme in android? 
how to make `notification.setNumber(Integer.parseInt(numberString));` can dynamic change from react-native? 

so, I can pass the real unread message to the app icon badges in android.

**Comment by phongcao** [comment]
@lauming1111 Try adding "number" in your notification payload:

https://github.com/CatalystCode/react-native-azurenotificationhub/blob/7275f6c1d5753ea7f50deb037aa010fcc6d74584/android/src/main/java/com/azure/reactnative/notificationhub/ReactNativeNotificationsHandler.java#L130
