### ISSUE TITLE
Exception register:config:resolver: is not a recognized Objective-C method

### ISSUE THREAD

**Issue by fedefrei** [CatalystCode/react-native-azurenotificationhub#136]
![IMG_8E751D8332AA-1](https://user-images.githubusercontent.com/7881911/78465603-43241480-76ce-11ea-8346-ac48b206e90b.jpeg)

Trying to implement push notifications on iOS I'm getting this error when trying to run on the device.

## Report

- [x] I have searched [existing issues](https://github.com/CatalystCode/react-native-azurenotificationhub/issues) and this is not a duplicate.

## Environment

- Platforms: iOS

- Android version: 

- iOS version: 13.3.1 (iPad)

## Issues and Steps to Reproduce
***Replaces this with steps to repro your issue, if applicable.***
Installed everything. Launched the app and happens every time when trying to register. Hub registers, but the register function itselfs fails.

## Expected Behavior
***Describe what you expected would happen.***
Register the app as Android does.

## Actual Behavior
***Describe what actually happened. Include screenshots, if applicable.***
Runtime error, looks like something is mislinked.

## Link to Code
***If you have some code that maintainers can clone/test for themselves, bugs can be resolved much faster. Please paste a link here.***

**Comment by phongcao** [comment]
I've just tried a fresh setup on an iPhone (13.4) using v095 and couldn't reproduce this issue. Can you share some sample code about your registration method?

**Comment by fedefrei** [comment]
I'm calling it like this:

on app constructor I do

```
export default class App extends React.Component {
constructor(props){
		super(props);
		if( Platform.OS === "android" ){
			PushNotificationEmitter.addListener(EVENT_REMOTE_NOTIFICATION_RECEIVED, this._onRemoteNotification);
			this.register();
		}

		if ( Platform.OS === "ios" ){
			this.requestPermissions();
		}

	}
}
```

then on request permissions : 

```
requestPermissions() {
		// register: Fired when the user registers for remote notifications. The
		// handler will be invoked with a hex string representing the deviceToken.
		NotificationHub.addEventListener('register', this._onRegistered.bind(this));
	
```

On registered goes like this:

```
_onRegistered(deviceToken) {
		remoteNotificationsDeviceToken = deviceToken;

		this.register();
	  }
```

and finally register: 

```
register() {
		if ( Platform.OS === "android" )
		{
			PushNotificationEmitter.addListener(EVENT_AZURE_NOTIFICATION_HUB_REGISTERED, this._onAzureNotificationHubRegistered);
			PushNotificationEmitter.addListener(EVENT_AZURE_NOTIFICATION_HUB_REGISTERED_ERROR, this._onAzureNotificationHubRegisteredError);
		
			NotificationHub.register({
			connectionString,
			hubName,
			senderID,
			tags,
			channelName,
			channelImportance,
			channelShowBadge,
			channelEnableLights,
			channelEnableVibration
			})
			.then((res) => console.warn(res))
			.catch(reason => console.warn(reason));
		}
		else{
			NotificationHub.register(remoteNotificationsDeviceToken, { connectionString, hubName, tags })
			.then((res) => console.warn(res))
			.catch(reason => console.warn(reason));
		}
	  }
```

Is that making sense? I'm wondering if I should call requestPermissions on the constructor.

**Comment by phongcao** [comment]
It makes sense. Seems to me that there is some components that haven't been initialized properly at the time you invoked `NotificationHub.register(...)` so can you try moving `requestPermissions` method out of your constructor? Maybe just for quickly testing, create a requestPermissions button and click on it.

**Comment by fedefrei** [comment]
Will check that.

**Comment by fedefrei** [comment]
I've set a 10 seconds timer after _onRegistered(deviceToken) is called but I keep getting the same error...

```
Exception 'register:config:resolver: is not a recognized Objective-C method.' was thrown while invoking register on target AzureNotificationHubManager with params (
    {TOKEN},
        {
        connectionString = "Endpoint BLA BLA ";
        hubName = bla  bla;
        tags =        (
        );
    },
    2428,
    2429
)
callstack: (
	0   CoreFoundation                      0x00000001a2cf4a5c 7519E999-1053-3367-B9D5-8844F6D3BDC6 + 1227356
	1   libobjc.A.dylib                     0x00000001a2a1bfa4 objc_exception_throw + 56
	2   CoreFoundation                      0x00000001a2bf6e88 7519E999-1053-3367-B9D5-8844F6D3BDC6 + 188040
	3   Foundation                          0x00000001a307b044 7B1733B1-74C9-3A33-8A58-853B0A029826 + 876612
	4   ExperimentaAzulApp                  0x00000001048e7974 -[RCTModuleMethod processMethodSignature] + 1060
	5   ExperimentaAzulApp                  0x00000001048eff68 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 180
	6   ExperimentaAzulApp                  0x000000010498b894 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 664
	7   ExperimentaAzulApp                  0x000000010498b418 _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 132
	8   ExperimentaAzulApp                  0x000000010498b388 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 28
	9   libdispatch.dylib                   0x00000001a29c0610 B9D95EAB-9269-367D-B2F4-C2B45821A32D + 374288
	10  libdispatch.dylib                   0x00000001a29c1184 B9D95EAB-9269-367D-B2F4-C2B45821A32D + 377220
	11  libdispatch.dylib                   0x00000001a2973190 B9D95EAB-9269-367D-B2F4-C2B45821A32D + 57744
	12  CoreFoundation                      0x00000001a2c725e4 7519E999-1053-3367-B9D5-8844F6D3BDC6 + 693732
	13  CoreFoundation                      0x00000001a2c6d5d8 7519E999-1053-3367-B9D5-8844F6D3BDC6 + 673240
	14  CoreFoundation                      0x00000001a2c6cadc CFRunLoopRunSpecific + 464
	15  GraphicsServices                    0x00000001acc0d328 GSEventRunModal + 104
	16  UIKitCore                           0x00000001a6d7a63c UIApplicationMain + 1936
	17  ExperimentaAzulApp                  0x00000001047d0cac main + 124
	18  libdyld.dylib                       0x00000001a2af6360 7B531A15-3E73-3185-90E2-B88D9476DA5E + 4960
)
```

**Comment by fedefrei** [comment]
I´ve set the exact example as my App but I keep getting that error.

**Comment by phongcao** [comment]
In your App.js file, can you confirm that you're import azure notification hub like this for iOS:

```js
const NotificationHub = require('react-native-azurenotificationhub/index.ios'); // NOT require('react-native-azurenotificationhub')
```

This is something easily overlooked. Also, are you using v095?

**Comment by fedefrei** [comment]
Yes sir, last version and I'm using react-native-azurenotificationhub/index.ios.
I'm on React Native 0.59.5 and xCode 10 I'm not sure if that makes a difference.

**Comment by phongcao** [comment]
I haven't used any RN version that is lower than 0.60 for a while so that might be the issue. I wonder if you set a break point in the native register method, does it get hit? Also, can you try reading the config object that it receives from the javascript layer? I can also try debugging with RN0.59.5 later when I have time.

**Comment by BrenoGO** [comment]
I solved the problem upgrading react native upper than 0.60.

**Comment by phongcao** [comment]
@BrenoGO Thanks for letting us know!

**Comment by kumarparth380** [comment]
@phongcao any other workaround/fix apart from upgrading the React-native version to above 0.60?
