### ISSUE TITLE
Not Receiving Notification on Android emulator if app is in background 

### ISSUE THREAD

**Issue by theromie** [CatalystCode/react-native-azurenotificationhub#146]
I have successfully register device using register() and able to get response of registerID but when i am trying to send notification from Test Send Azure Notification Hubs that time device Registration ID is also showing in results but no notification received on android emulator.

`remoteNotification = () => {
  PushNotificationEmitter.addListener(
    EVENT_REMOTE_NOTIFICATION_RECEIVED,
    this._onRemoteNotification
  );
};`

`
register = async (id) => {
  tags = [id.toString()];
  PushNotificationEmitter.addListener(
    EVENT_AZURE_NOTIFICATION_HUB_REGISTERED,
    this._onAzureNotificationHubRegistered
  );
  PushNotificationEmitter.addListener(
    EVENT_AZURE_NOTIFICATION_HUB_REGISTERED_ERROR,
    this._onAzureNotificationHubRegisteredError
  );
this._register(tags);
};
`

`_register = (tags) =>{
NotificationHub.registerTemplate({
    connectionString,
    hubName,
    senderID,
    template,
    templateName,
    tags,
    channelName,
    channelDescription,
    channelImportance,
    channelShowBadge,
    channelEnableLights,
    channelEnableVibration,
  })
    .then((res) => console.log(res))
    .catch((reason) => console.warn(reason));
};`

**Comment by theromie** [comment]
After adding Local Notification inside _onRemoteNotification it started working.

**Comment by BrenoGO** [comment]
What would be the "Local Notification inside _onRemoteNotification?!"

**Comment by theromie** [comment]
import react-native-notifications and inside _onRemoteNotification add 
`Notifications.postLocalNotification({
      title: title,
      body: `${notification.message}`,
      extra: 'data',
    });`
