### ISSUE TITLE
minSdkVersion 16 cannot be smaller than version 26 declared in library [:react-native-azurenotificationhub]

### ISSUE THREAD

**Issue by ahmadkhudeish** [CatalystCode/react-native-azurenotificationhub#147]
## Report

- [ yes] I have searched [existing issues](https://github.com/CatalystCode/react-native-azurenotificationhub/issues) and this is not a duplicate.

## Environment

- Platforms: Android

- Android version: 9

- iOS version: 

## Expected Behavior
***Describe what you expected would happen.***
I know this issue is because I have the gradle minSdkVersion < library version which makes it fail and when I upgrade gradle minSdkVersion >= 26 it succeeds. But if I use minSdkVersion 26 I would only be able to target ~60% of all android devices. I would love to be able to target a higher percentage. I know with some libraries it's hard to account for backward compatibility when developing new features.
Is it possible to run this library with minSdkVersion: 16 ?
And how do I do it? 

Thanks very much
## Actual Behavior
***Describe what actually happened. Include screenshots, if applicable.***
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 26 declared in library [:react-native-azurenotificationhub] ../node_modules/react-native-azurenotificationhub/android/build/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 16
  	Suggestion: use a compatible library with a minSdk of at most 16,
  		or increase this project's minSdk version to at least 26,
  		or use tools:overrideLibrary="com.azure.reactnative.notificationhub" to force usage 
(may lead to runtime failures)

**Comment by antonandreyev** [comment]
That's right. I see the commit changing min sdk from 16 to 26 was done only 9 days ago. Is there any reason we are restricted to Android 8 and above? If so please maintainers change the readme because it reduces the usabulity of the library a lot. Meanwhile we can use v0.9.5 (not patched) in which we don't have this restriction.

**Comment by phongcao** [comment]
At first, I thought that it would be a good idea to upgrade the min sdk to increase the compatibility with some new react libraries. However, this turns out to be causing more trouble than helping so I'll submit a PR to revert this change later this week.
@vishal-techbitsolution You can continue to use v0.9.5 patched version.

**Comment by vishal-techbitsolution** [comment]
Hey @phongcao Thanks, But I have a query, The notification API require min sdk version 26, this is the main reason I requested to update minsdk version. But if its changed to 16, won't it have any effect with newer updates.

**Comment by ahmadkhudeish** [comment]
Hey @phongcao I'm still having issues with this bug, when will this be fixed? thanks

**Comment by phongcao** [comment]
> Hey @phongcao I'm still having issues with this bug, when will this be fixed? thanks

@ahmadkhudeish Please use [v0.9.5](https://github.com/CatalystCode/react-native-azurenotificationhub/tree/v0.9.5) (not patched) for now. I'll update master whenever I have a chance this week.

**Comment by phongcao** [comment]
> Hey @phongcao Thanks, But I have a query, The notification API require min sdk version 26, this is the main reason I requested to update minsdk version. But if its changed to 16, won't it have any effect with newer updates.

@vishal-techbitsolution Future updates will be using min sdk version 16 since we want to support older Android devices.

**Comment by ahmadkhudeish** [comment]
@phongcao great thanks, looking forward to it

**Comment by aprilmintacpineda** [comment]
Still exists today. Requiring us to change minSdkVersion to 26
