### ISSUE TITLE
"Native Module cannot be null" on iOS

### ISSUE THREAD

**Issue by classtronaut** [CatalystCode/react-native-azurenotificationhub#163]
## Report

- [ x ] I have searched [existing issues](https://github.com/CatalystCode/react-native-azurenotificationhub/issues) and this is not a duplicate.

## Environment

- iOS version: 13.5.1

## Issues
I am receiving the error `Invariant Violation: Native module cannot be null.` whenever I try and use the hub provided by `require('react-native-azurenotificationhub/index.ios')`. I also receive the error `Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)` but I'm not sure that this is related. I followed the installation instructions for iOS. I've googled around and done a ton of cache busting and uninstalls/reinstalls between npm and pod, no luck. I'm hoping I missed something simple? The android side of the code works fine.

**Comment by swizes** [comment]
I am facing the same issue, using latest version of rwact native and using the module version 0.95 (not the patched one)

**Comment by classtronaut** [comment]
Not sure if this will be the solution for anyone else running into this but my problem ended up being that I was trying to import the ios notification hub as `const iosNotificationHub = require('react-native-azurenotificationhub/index.ios');` instead of as the example name `NotificationHub`. When I change that back things run properly.
