### ISSUE TITLE
Issue with iOS registration (Unauthorized)

### ISSUE THREAD

**Issue by sudhirnumino** [CatalystCode/react-native-azurenotificationhub#20]
Getting an error "Unauthorized" for the token. Also the API version is specified as 2013-04 whereas the latest version is 2015-01.

Is the SharedAccessSignature token generation logic is changed from the API version?

**Comment by rozele** [comment]
cc @phongcao

**Comment by rozele** [comment]
@sudhirnumino I think this was because I hadn't published a new version of the NPM package. Closing now that 0.2.0 is published. Please re-open if this remains an issue.

**Comment by sudhirnumino** [comment]
Still getting _401:Unauthroized_  error for the registration, with iOS v11.1

**Comment by sudhirnumino** [comment]
Attached the error message 
![error](https://user-images.githubusercontent.com/26406228/32488810-eb7ff33e-c3d3-11e7-8500-8f635437a4ad.png)

**Comment by phongcao** [comment]
Hi @sudhirnumino, thanks for informing us. I'll have a look at this issue as soon as I have time.

**Comment by sudhirnumino** [comment]
@phongcao Tested this with a clean setup for my app, works perfectly. Not able to reproduce the above "Unauthorized" error. You may close the above issue. 

Thanks a ton.

**Comment by phongcao** [comment]
Awesome, thanks for telling me.

**Comment by dipernaa** [comment]
I am getting the same error.
iOS v11.1
react-native-azurenotificationhub v0.3.0

**Comment by matt-landers** [comment]
I'm getting the same error. Any idea how to correct it? Android works fine.
