### ISSUE TITLE
Did iOS support not make it into a new release? 

### ISSUE THREAD

**Issue by Maj0rPaine** [CatalystCode/react-native-azurenotificationhub#21]
v0.1.0 seems to be the only release and npm is referencing this version.

**Comment by phongcao** [comment]
@rozele Can we release a new version on nuget?

**Comment by rozele** [comment]
Yep! I'll try to publish today. Thanks @phongcao!

**Comment by Maj0rPaine** [comment]
Awesome! Thanks for your work on this.

**Comment by sudhirnumino** [comment]
Great !! Thanks @rozele & @phongcao 
Waiting to try out the latest one.

**Comment by rozele** [comment]
Published latest iOS changes.
