### ISSUE TITLE
Android Marshmallow Integration issue

### ISSUE THREAD

**Issue by KarthickCSK** [CatalystCode/react-native-azurenotificationhub#25]
Is this module functioning for android 6. I tried to install followed all the instructions .Build was successful but no registrations happened.Moreover there is no way to confirm that registration was successful. No error was thrown stating the same.

**Comment by phongcao** [comment]
Hi KarthickCSK, the Android module was developed quite long time ago so it might not work well with Android 6. We'll check and get back to you later.

**Comment by KarthickCSK** [comment]
Thanks . Meanwhile i will send you the log details. where i am facing error.So it wil speed up your process

**Comment by KarthickCSK** [comment]
Error 1 : 

error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
:react-native-azurenotificationhub:compileReleaseJavaWithJavac FAILED

Error 2:

 Manifest merger failed : Attribute application@icon value=(@mipmap/ic_launcher) from AndroidManifest.xml:17:7-41
     is also present at [com.microsoft.azure:azure-notifications-handler:1.0.1] AndroidManifest.xml:13:9-45 value=(@drawable/ic_launcher).
  Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:13:5-42:19 to override.

**Comment by phongcao** [comment]
Hi @KarthickCSK, I've just merged a PR that fixes error 1. Error 2 is #13, the temporary workaround is removing the android icon tag.

**Comment by KarthickCSK** [comment]
Thanks, but the app is still not working . I found a detail in the log file.

**Failed to complete token refresh
     java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.azurernnotifications. Make sure to call FirebaseApp.initializeApp(Context) first.**

Please look into the above issue i tried to get around but no luck

**Comment by phongcao** [comment]
@KarthickCSK We need to follow the exact steps of "Add Firebase to your Android app" so that [FirebaseApp](https://firebase.google.com/docs/reference/android/com/google/firebase/FirebaseApp) can be initialized successfully:

**Step 1**

![1](https://user-images.githubusercontent.com/9741323/34632568-32429eb8-f244-11e7-93f1-fa95aa15d55e.JPG)

**Step 2**

![2](https://user-images.githubusercontent.com/9741323/34632579-403d75f6-f244-11e7-8fdc-bf90cab27717.JPG)
