### ISSUE TITLE
npm install missing WindowsAzureMessaging-prefix.pch

### ISSUE THREAD

**Issue by keung7251** [CatalystCode/react-native-azurenotificationhub#26]
Showing Recent Issues
No such file or directory: 'node_modules/react-native-azurenotificationhub/ios/WindowsAzureMessaging/WindowsAzureMessaging-Prefix.pch'

**Comment by phongcao** [comment]
@keung7251 Can you try our master branch?

**Comment by phongcao** [comment]
Please re-open if needed.
