### ISSUE TITLE
android not working 

### ISSUE THREAD

**Issue by keung7251** [CatalystCode/react-native-azurenotificationhub#27]
react-native-azurenotificationhub/android/src/main/java/com/azure/reactnative/notificationhub/ReactNativeNotificationHubPackage.java:19: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
:react-native-azurenotificationhub:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-azurenotificationhub:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by phongcao** [comment]
This issue has been fixed on master. See #24.

**Comment by phongcao** [comment]
@rozele It may be worth releasing a new npm version that has this issue fixed. It'll surely help our developers time.
