### ISSUE TITLE
Unregister in Android

### ISSUE THREAD

**Issue by PanRada** [CatalystCode/react-native-azurenotificationhub#32]
Hi 

Wondering if some one can answer:
unregister() is now deprecated:
https://developers.google.com/android/reference/com/google/android/gms/gcm/GoogleCloudMessaging.html#unregister()

we are use that  in react-native-azurenotification and notice errors 
My issues is to any time when user update tags to update register method with new tags. for Android is not updated. is any way to solve this problem ?
hope for quick solution, direction

**Comment by phongcao** [comment]
Please try again in the latest version and let me know if it still occurs.
