### ISSUE TITLE
FCM token null after NotificationHub.unregister()

### ISSUE THREAD

**Issue by Maj0rPaine** [CatalystCode/react-native-azurenotificationhub#34]
After unregistering with Azure and trying to register again, FirebaseInstanceId.getInstance().getToken() is returning a null token. Is this expected behavior?

The conditional statement in the code below is failing because the hub is trying to register with a null token from the token refresh. 

This line throws an exception:
` regID = hub.register(token, tags).getRegistrationId();`

String token = FirebaseInstanceId.getInstance().getToken();
Log.d(TAG, "FCM Registration Token: " + token);

// Storing the registration ID indicates whether the generated token has been
// sent to your server. If it is not stored, send the token to your server.
// Also check if the token has been compromised and needs refreshing.
if (regID == null || storedToken != token) {
    NotificationHub hub = new NotificationHub(hubName, connectionString, this);
    Log.d(TAG, "NH Registration refreshing with token : " + token);
    regID = hub.register(token, tags).getRegistrationId();
    Log.d(TAG, "New NH Registration Successfully - RegId : " + regID);
    notificationHubUtil.setRegistrationID(this, regID);
    notificationHubUtil.setFCMToken(this, token);
}

**Comment by rogarMS** [comment]
Hey @Maj0rPaine,
Just ran into this for my app. Did you figure anything out?

**Comment by Maj0rPaine** [comment]
@rogarMS I did not. Best practice imo would be to not allow someone to unregister with Azure. Simply point them to the device settings to manage push notifications.

**Comment by phongcao** [comment]
Closing this for now. Let me know if this is something that is still important for you.
