### ISSUE TITLE
My Android app gradle build perfectly, but crashes on debug mode

### ISSUE THREAD

**Issue by vasukumar169** [CatalystCode/react-native-azurenotificationhub#35]
Hi,
My android app crashes as soon as the apk installs and and launches the app.
Neither it is recording any of the crash analytics for the same.

React Native version 0.47.1

adb shell am start -n "com.hm/com.hm.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Client not ready yet..Connected to process 4253 on device samsung-sm_j700f-5203106cfafd5373
Application terminated.

**Comment by phongcao** [comment]
@vasukumar169 Can you please provide more info in logcat?

**Comment by phongcao** [comment]
Closing. Feel free to re-open if it still happens.
