### ISSUE TITLE
Register dosen't happen

### ISSUE THREAD

**Issue by NawazKhanMd** [CatalystCode/react-native-azurenotificationhub#36]
After Register is initiated from mobile nothing happens i have put logs at 

`Intent intent = new Intent(reactContext, ReactNativeRegistrationIntentService.class);
        reactContext.startService(intent);
        NotificationsManager.handleNotifications(reactContext, senderID, ReactNativeNotificationsHandler.class);`

i have put a log there This was excuting after that I could not figure out whats happening

I have checked in cloud explorer where my  registered device list is visible 

I didnt see any devices there 

Pls help me :)

**Comment by phongcao** [comment]
@NawazKhanMd Please check #43 and see if it helps you.
