### ISSUE TITLE
[iOS] Private headers causes Archive to fail

### ISSUE THREAD

**Issue by Ladekarl** [CatalystCode/react-native-azurenotificationhub#40]
Hi. 

First of all thank you for bringing this functionality to react native.

I found an issue when trying to archive my iOS application after linking this library.
The WindowsAzureMessaging target has private headers.

![screen shot 2018-05-23 at 14 11 18](https://user-images.githubusercontent.com/6671635/40423590-59e48cd6-5e93-11e8-82ed-fb6b63d1188b.png)

This causes xcode to archive the project as a generic archive instead of as an iOS app since the private headers are not copied to the application.

The workaround is to copy all the headers from private to project.

![screen shot 2018-05-23 at 14 22 05](https://user-images.githubusercontent.com/6671635/40424263-5c5568ee-5e95-11e8-9ee1-24444caef438.png)

**Comment by phongcao** [comment]
Thanks @stephenvisser and @Ladekarl !
