### ISSUE TITLE
Unable to retrieve Azure registration id on using onAzureNotificationHubRegistered

### ISSUE THREAD

**Issue by munna-singh** [CatalystCode/react-native-azurenotificationhub#41]
@rozele, 

After registering a device (both Android and iOS) with Azure, is there a way to retrieve the Azure registration id? Currently, the function only returns a JSON with the registration status of success or failure. 

Thoughts? 
Munna

**Comment by phongcao** [comment]
@munna-singh Can you check #46? Is it something you're looking for?

**Comment by munna-singh** [comment]
@phongcao  Yes, this is what i was looking for. Thank you very much.
