### ISSUE TITLE
Device Registration is not happening

### ISSUE THREAD

**Issue by VenkataPakalapati** [CatalystCode/react-native-azurenotificationhub#43]
Hi I implemented all the steps provided in the tutorial. However the register method does not seem to work. It does not throw any error either

I don't see the device in the notification hub registered devices list. I tried sending a test push notifcation from azure portal without any tag and with tag I used in the app. It says "Message was successfully sent, but there were no matching targets".

Please advise

**Comment by phongcao** [comment]
@VenkataPakalapati Can you let me know your device OS?

**Comment by VenkataPakalapati** [comment]
I am using Google pixel 2 xl running Android 8.1.0

**Comment by phongcao** [comment]
@VenkataPakalapati Can you check logcat and look for the highlighted part in the below picture?

![debug](https://user-images.githubusercontent.com/9741323/42175322-07fe1688-7df3-11e8-8014-279cc10934f9.JPG)

Also, the test message must contain the **id** field, which is a number, so that it can be processed. For example:

{"data":{"id":12345, "message":"Notification Hub test notification"}}

I'm using Android 7.0 right now but it should work for your device.

**Comment by VenkataPakalapati** [comment]
Thanks for responding.I am using an emulator and my IDE is Visual Studio code.I setup a break point at register method ran my code .The breakpoint gets hit and i dont see anything in logcat.
I tried sending a test push notification from azure like you suggested.No luck

<img width="1524" alt="github_isssue" src="https://user-images.githubusercontent.com/17863587/42185591-6bcd22ac-7e17-11e8-871c-95038137d7d9.PNG">


<img width="693" alt="github_isssue2" src="https://user-images.githubusercontent.com/17863587/42185629-955d4f84-7e17-11e8-873e-f237743bf268.PNG">

**Comment by phongcao** [comment]
Can you try using a real device to test it?

**Comment by phongcao** [comment]
You can use ""adb logcat" command line to check for that log info.

https://developer.android.com/studio/command-line/logcat

**Comment by VenkataPakalapati** [comment]
Thanks. i managed to get the registration working .However once i send a test push notiifcation,it seems my phone receives it ,but it crashes the app

<img width="828" alt="github_isssue4" src="https://user-images.githubusercontent.com/17863587/42297463-9793bba0-7fcd-11e8-991a-75c0a0674acb.PNG">
<img width="1554" alt="github_isssue5" src="https://user-images.githubusercontent.com/17863587/42297464-97a0df9c-7fcd-11e8-84ac-d0598eb9526b.PNG">
<img width="1345" alt="github_isssue6" src="https://user-images.githubusercontent.com/17863587/42297465-97acbcd6-7fcd-11e8-9590-3361f29e4f74.PNG">

**Comment by phongcao** [comment]
@VenkataPakalapati Did you manage to solve your issue? Feel free to open a new one if needed.

**Comment by theromie** [comment]
**Failed to complete token refresh**
Earlier it was working but it stopped working.

2020-05-07 19:26:47.354 9523-9855/PACKAGE I/ReactNativeNotifs: Manual token refresh => publishing existing token (TOKEN)
2020-05-07 19:26:48.062 9523-9860/PACKAGE  D/ReactNativeRegistration: FCM Registration Token: TOKEN
2020-05-07 19:26:48.065 9523-9860/PACKAGE  D/ReactNativeRegistration: NH Registration refreshing with token : TOKEN
2020-05-07 19:27:28.137 9523-9860/PACKAGE  E/ReactNativeRegistration: Failed to complete token refresh
