### ISSUE TITLE
Handling clicking on notification

### ISSUE THREAD

**Issue by kmarkiewicz** [CatalystCode/react-native-azurenotificationhub#50]
I am just wondering how I can handle when a user taps on the notification when the application is not open?
I can see that the onRemoteNotification gets run when you tap on a notification while the app is in the foreground. However, if you close the application and tap on a notification, nothing gets run.
How do I handle this?

Thank you!

**Comment by phongcao** [comment]
@kmarkiewicz Can you try this PR?

https://github.com/CatalystCode/react-native-azurenotificationhub/pull/51

**Comment by kmarkiewicz** [comment]
I have not implemented your PR yet, because the Notifications stopped working now and my app keeps crashing when trying to register with Azure. The onNotificationRegisterError is returning "Error: pns handle". I have spent hours trying to fix this and I cannot.
Sorry, I can't tell you if your PR works for me or not.
