### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by yasaricli** [CatalystCode/react-native-azurenotificationhub#53]
hello, I am getting an error in this way on android,

```
> Task :react-native-azurenotificationhub:compileDebugJavaWithJavac FAILED
/Users/Y/Desktop/mobile/node_modules/react-native-azurenotificationhub/android/src/main/java/com/azure/reactnative/notificationhub/ReactNativeNotificationsHandler.java:117: error: constructor Builder in class Builder cannot be applied to given types;
            NotificationCompat.Builder notification = new NotificationCompat.Builder(context, NOTIFICATION_CHANNEL_ID)
```

react-native: 0.57.0

ext config

![screen shot 2018-10-03 at 12 32 43](https://user-images.githubusercontent.com/1306620/46402467-75833900-c708-11e8-8ce2-0a1d98b7ff3f.png)

**Comment by benlime** [comment]
For me, updating the dependencies in the android project worked. See my PR https://github.com/CatalystCode/react-native-azurenotificationhub/pull/56
