### ISSUE TITLE
iOS :Lexical or PreProcessor Issue "React/RCTEventEmitter.h" file not found

### ISSUE THREAD

**Issue by porjegirish** [CatalystCode/react-native-azurenotificationhub#55]
I have Pods project while building the project it gives error Lexical or PreProcessor Issue "React/RCTEventEmitter.h" file not found. It is not getting ref for RCTEventEmitter file while building.

**Comment by MD1990** [comment]
I am also facing this issue, from the help on the internet I am getting for specific packages and not help for this plugin I am using, any updates on this.

**Comment by phongcao** [comment]
Please try the latest version and re-open if it stills happen.
