### ISSUE TITLE
Cannot Receive Notifications when the app is in kill state.

### ISSUE THREAD

**Issue by devnitish29** [CatalystCode/react-native-azurenotificationhub#57]
I am getting notifications when the Android  App is in the Foreground/Background state but when the app is killed. I am not receiving any notifications. Do we have any implementations so that I can see what I am doing wrong?

**Comment by illidandh** [comment]
i'm facing this issue too , anyone have solution ?

**Comment by sumesh1993** [comment]
make sure your payload is of the following format
`data: {
    id: 123,
    title: "welcome",
    message:"to your app" ,
  }`

**Comment by illidandh** [comment]
@sumesh1993 thank you , its work.
do you know handle click on notification when killed app ( not background ) addEventListener not working
