### ISSUE TITLE
Android is not working

### ISSUE THREAD

**Issue by wyrustaaruz** [CatalystCode/react-native-azurenotificationhub#58]
Hello,
I created a new blank project with `react-native init asd` then I added your lib. with `npm install react-native-azurenotificationhub` then I made settings with your documentation. Finally I wrote `react-native run-android` in console. Result is : Build Failed.

<img width="1494" alt="ekran resmi 2019-02-22 11 48 28" src="https://user-images.githubusercontent.com/7090553/53230479-d0a5d000-3697-11e9-8acf-3584bd1b333f.png">
code is below:

`Hasan-MacBook-Pro:asd hasanrizauzuner$ react-native run-android
Starting JS server...
Building and installing the app on the device (cd android && ./gradlew installDebug)...

> Configure project :app
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (28.0.2) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.2.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '28.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Configure project :react-native-azurenotificationhub
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (26.0.3) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.2.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :app:processDebugManifest FAILED
/Users/hasanrizauzuner/Desktop/asd/android/app/src/main/AndroidManifest.xml:16:7-34 Error:
        Attribute application@allowBackup value=(false) from AndroidManifest.xml:16:7-34
        is also present at [com.microsoft.azure:azure-notifications-handler:1.0.1] AndroidManifest.xml:12:9-35 value=(true).
        Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:9:5-40:19 to override.

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:16:7-34
        is also present at [com.microsoft.azure:azure-notifications-handler:1.0.1] AndroidManifest.xml:12:9-35 value=(true).
        Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:9:5-40:19 to override.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUİLD FAILED in 1s
16 actionable tasks: 1 executed, 15 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

Command failed: ./gradlew installDebug

Error: Command failed: ./gradlew installDebug
    at checkExecSyncError (child_process.js:621:11)
    at Object.execFileSync (child_process.js:639:13)
    at runOnAllDevices (/Users/hasanrizauzuner/Desktop/asd/node_modules/react-native/local-cli/runAndroid/runAndroid.js:299:19)
    at buildAndRun (/Users/hasanrizauzuner/Desktop/asd/node_modules/react-native/local-cli/runAndroid/runAndroid.js:135:12)
    at isPackagerRunning.then.result (/Users/hasanrizauzuner/Desktop/asd/node_modules/react-native/local-cli/runAndroid/runAndroid.js:65:12)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)`

**Comment by nikith050** [comment]
@wyrustaaruz, Check your manifest file and change android:allowBackup="false" to android:allowBackup="true". Should work fine
