### ISSUE TITLE
Publish new npm version

### ISSUE THREAD

**Issue by matt-landers** [CatalystCode/react-native-azurenotificationhub#59]
Can someone publish a new npm version with the updates to the google services in the gradle file? I'm changing it locally, but when others pull it down they have to change it as well. This is related to #53 and #56. 

Thanks!

**Comment by phongcao** [comment]
[0.6.0](https://www.npmjs.com/package/react-native-azurenotificationhub/v/0.6.0) has been published.

**Comment by matt-landers** [comment]
@phongcao Thanks!
