### ISSUE TITLE
GCM is deprecated

### ISSUE THREAD

**Issue by sumesh1993** [CatalystCode/react-native-azurenotificationhub#63]
So, the underlying code of this library uses gcm, which as per google has been deprecated and will stop working from 29th May'19.
`FirebaseInstanceId.getInstance().getToken();`, android studio also suggests that `getToken()` is deprecated.
Just wanted to understand here, will this affect my application after 29thMay once GCM stops working ?
Are there any plans to migrate this library to completely FCM ?

Your response will be highly appreciated

**Comment by phongcao** [comment]
@sumesh1993 Good call. It looks pretty straightforward to use the new APIs to obtain the token so I'll spend sometime this week to check it.

**Comment by sumesh1993** [comment]
@phongcao that would be great, thank you.

**Comment by sumesh1993** [comment]
@phongcao Hi, any update on this ?

**Comment by phongcao** [comment]
@sumesh1993 I checked and there is a problem with [azure-mobile-services](https://github.com/Azure/azure-mobile-services), which this library depends on. At the moment, Mobile Services is deprecated and it's [using GCM](https://github.com/Azure/azure-mobile-services/blob/master/sdk/android/src/notifications-handler/src/main/java/com/microsoft/windowsazure/notifications/NotificationsManager.java#L10). Can you try [App Center Push](https://docs.microsoft.com/en-us/appcenter/sdk/push/react-native-android) instead?

**Comment by phongcao** [comment]
I made some changes to the library but still there is a lot of work related to Azure Mobile Services sdk:
https://github.com/CatalystCode/react-native-azurenotificationhub/tree/thcao/fcm

**Comment by phongcao** [comment]
@sumesh1993 Can you try this PR?

https://github.com/CatalystCode/react-native-azurenotificationhub/pull/64

**Comment by sumesh1993** [comment]
ok i'll check it out and get back to you

**Comment by sumesh1993** [comment]
@phongcao after migration to fcm as instructed, i am unable to receive notifications on android.
FCM token is getting generated successfully. My tag is also getting registered, i successfully receive the registration ID.
But when i use test send from azure to trigger a notification, it says sent successfully. But nothing is received on my android device.
What could i be doing wrong ?
Your response will be highly appreciated

**Comment by sumesh1993** [comment]
@phongcao Can u help me out pls ? I m stuck. Please refer [this](https://stackoverflow.com/questions/56078899/react-native-azure-notification-hub) stackoverflow question.

**Comment by phongcao** [comment]
This is very strange. I can spend some time this week to test it again and let you know.

**Comment by sumesh1993** [comment]
@phongcao The thing is i have integrated this library in one of my client projects and because GCM is getting deprecated in 2 weeks, my clients are panicking.
You would be really helping me out if you could close this issue asap.

Appreciate the effort you are putting into it. Thanks.

**Comment by sumesh1993** [comment]
@phongcao Hi, did u get a chance to look at it ?

**Comment by phongcao** [comment]
@sumesh1993 Unfortunately, I'm not available now but I can have a look at it on the weekend.

**Comment by sumesh1993** [comment]
@phongcao One more thing, i tried sending notification from the fcm console using the fcm token that is generated. I was able to receive the notification via fcm directly.
Not sure why its not working through azure

**Comment by sumesh1993** [comment]
@phongcao any update ?

**Comment by phongcao** [comment]
I've just published v0.8.0 that should fix the notification issue. There is still another issue with [azure-mobile-services](https://github.com/Azure/azure-mobile-services) sdk, which is still using some deprecated APIs from GCM. I'll be checking it this week to see if I can upgrade that sdk to fully use FCM.

**Comment by sumesh1993** [comment]
@phongcao so this version of the library will stop working after 29th May ?

**Comment by phongcao** [comment]
@sumesh1993 Try out v0.9.0. It shouldn't have any dependency on GCM.
