### ISSUE TITLE
Android not receiving notifications

### ISSUE THREAD

**Issue by davidbutz** [CatalystCode/react-native-azurenotificationhub#65]
Hello,

I am successfully getting notifications through iOS, and used to get them through Android. Until recently.

Wondering if "GCM is deprecated #63" issue is affecting me? 

I am testing with Azure "Test Send" with particular id targeted, but never see the notifications pop up.  Nothing on adb log... just dead silence with the installation instructions provided. 

What I am asking: Is there a way to trouble shoot the react-receiver side without doing something like "https://docs.microsoft.com/en-us/azure/notification-hubs/notification-hubs-android-push-notification-google-fcm-get-started" and cluttering up my pristine .58 react install (I don't want to build classes in Android Studio)...

Any ideas would be welcome.

**Comment by davidbutz** [comment]
I forgot to mention one delta, a critical one from your install instructions.

I could not get a release variant to run with the versions of
com.google.android.gms:play-services-gcm & com.google.firebase:firebase-messaging in the instructions. I was getting errors in the release variant version.

So I updated to
    compile 'com.google.android.gms:play-services-gcm:16.1.0'
    compile 'com.google.firebase:firebase-messaging:17.6.0'

**Comment by phongcao** [comment]
@davidbutz I've just pushed the fix for the compiling issue in release configuration in #64. Regarding the notification issue, did you receive the registration ID after registering?

**Comment by davidbutz** [comment]
Hello Phong,

Yes I did receive the registrationId.

Where I am: When the app is running, I can Toast.Show the message coming in. It looks like I had some code which expected the notification coming to be an object, when it now is coming as a String. 
So I now test to see if it’s an object or string and handle it appropriately:

Another example:

I believe I used to get:

{”google.delivered_priority”:“normal”,“google.sent_time”:1555594027305,“google.ttl”:2419200,“google.original_priority”:“normal”,“from”:“201610825910”,“google.message_id”:“0:1555594027312388%d483c22ff9fd7ecd”,“message”:“Notification Hub test notification”}

Now I get:

“{”google.delivered_priority”:“normal”,“google.sent_time”:1555594027305,“google.ttl”:2419200,“google.original_priority”:“normal”,“from”:“201610825910”,“google.message_id”:“0:1555594027312388%d483c22ff9fd7ecd”,“message”:“Notification Hub test notification”}”




Perhaps that helps with the next part:

I don’t get notifications when the app is not on-screen/open. They are just not showing up. 

Thanks a ton!


David Butz
davidthomasbutz@gmail.com
(c) 410-218-6131

**Comment by davidbutz** [comment]
Hello phongcao ,

wondering if you have any advice on why my android machine will receive notifications when in app, but not when the app is closed?

Thanks,

Dave Butz

**Comment by davidbutz** [comment]
All is good. I noticed the missing "id" from the payload and now works like a charm.

**Comment by phongcao** [comment]
@davidbutz The "id" issue has also been fixed on master: https://github.com/CatalystCode/react-native-azurenotificationhub/pull/61

Thanks for letting me know.
