### ISSUE TITLE
Question: How does this relate to the core RN pushnotification documentation?

### ISSUE THREAD

**Issue by askpatrickw** [CatalystCode/react-native-azurenotificationhub#69]
On the RN site there is documentation related to the [PushNotificationiOS component](https://facebook.github.io/react-native/docs/pushnotificationios).

Can you briefly explain how these are related (or not) when using Azure Notification Hub? I'll follow-up with a PR to add to this to the docs.

tx!

**Comment by phongcao** [comment]
@askpatrickw `PushNotificationIOS` component doesn't support Azure Notification Hub by default. This library does and is built on top of that component.
