### ISSUE TITLE
Missing CocoaPods for iOS

### ISSUE THREAD

**Issue by fylock** [CatalystCode/react-native-azurenotificationhub#70]
Could we get this published as a CocoaPod for iOS? Now that ReactNative is moving to CocoaPods, we should do the same with our packages.

**Comment by jonathanort** [comment]
Just created a PR that adds support for React Native 0.60 and Cocoapods

**Comment by jonathanort** [comment]
Just created a PR that adds support for React Native 0.60 (Cocoapods) https://github.com/CatalystCode/react-native-azurenotificationhub/pull/71
