### ISSUE TITLE
not supported in the simulator

### ISSUE THREAD

**Issue by yasaricli** [CatalystCode/react-native-azurenotificationhub#72]
How do we support simulator for ios?

<img width="685" alt="Screen Shot 2019-08-23 at 17 16 41" src="https://user-images.githubusercontent.com/1306620/63599184-c4101f00-c5c9-11e9-9488-d1fec2217418.png">

**Comment by phongcao** [comment]
You can use [SimulatorRemoteNotifications](https://github.com/acoomans/SimulatorRemoteNotifications) to simulate sending remote notifications to your app.
