### ISSUE TITLE
Distinguish if app is opened or closed while receiving notification

### ISSUE THREAD

**Issue by anikhechoyantumo** [CatalystCode/react-native-azurenotificationhub#73]
We have `remoteNotificationReceived` event, which (in my tests) is called when
1. app is opened and a notification is received
2. app is closed, opened on tapping a notification
3. app is in background, notification is received and after some time app goes to foreground again

I need to handle these scenarios differently. Is there a way to differentiate them?

**Comment by anikhechoyantumo** [comment]
There is one more case... when app comes to foreground from background state after tapping on a notification. Checking the AppState helped in this case, but not in last 2 of the list. When app is closed and opened by tapping a notification, the AppState is already active, when the event happens. In case of the 3rd case seems it calls twice, once with background state, once with active.

**Comment by chowkapo** [comment]
Does anyone come up with any solution? I also need to distinguish different cases upon arrival of a notification.

**Comment by anikhechoyantumo** [comment]
@chowkapo As a workaround for receiving part I subscribed to the firebase notifications listeners instead of azure's, because azure uses FCM under the hood. Solution worked for iOS, couldn't implement it for Android yet. I can share more details if needed.

**Comment by chowkapo** [comment]
@anikhechoyantumo please do share more details. Does that mean we have to give up this azure notification hub library and switch to something FCM specific? Thanks a lot!

**Comment by anikhechoyantumo** [comment]
I didn't stop using this library, because it supports azure registration, tags, etc. What i did is not listening to `remoteNotificationReceived` event. Instead, i listen to `onNotification`, `onNotificationOpened` and `getInitialNotification` events of `Firebase.notifications()` instance. Here is the example code:

`this.notificationListener = Firebase.notifications().onNotification(
      notification => {
        console.log("onNotification called");
        // handle receiving a notification
      }
    );

    /*
     * If app is in background, you can listen for when a notification is clicked / tapped / opened as follows:
     * */
    this.notificationOpenedListener = Firebase.notifications().onNotificationOpened(
      notificationOpen => {
        console.log("onNotificationOpened called");
        // handle tapping with notificationOpen.notification
      }
    );

    /*
     * If your app is closed, you can check if it was opened by a notification being clicked / tapped / opened as follows:
     * */
    const notificationOpen = await Firebase.notifications().getInitialNotification();
    if (notificationOpen) {
      console.log("onNotificationOpened called");
      // handle openning with notificationOpen.notification
    }`

For more information how to setup Firebase Notifications framework, please refer the official docs here:
https://rnfirebase.io/docs/v4.3.x/notifications/receiving-notifications

**Comment by ThabrezAhmed** [comment]
> I didn't stop using this library, because it supports azure registration, tags, etc. What i did is not listening to `remoteNotificationReceived` event. Instead, i use `onNotification`, `onNotificationOpened` and `getInitialNotification` methods of `Firebase.notifications()` instance.


I tried this solution. Unfortunately, no luck. Can you please share your code?

**Comment by anikhechoyantumo** [comment]
> > I didn't stop using this library, because it supports azure registration, tags, etc. What i did is not listening to `remoteNotificationReceived` event. Instead, i use `onNotification`, `onNotificationOpened` and `getInitialNotification` methods of `Firebase.notifications()` instance.
> 
> I tried this solution. Unfortunately, no luck. Can you please share your code?

On which platform have you tried? It worked only on iOS for me. If it's not working for you maybe it's because you missed something in messaging framework setup?

**Comment by ThabrezAhmed** [comment]
> On which platform have you tried? It worked only on iOS for me. If it's not working for you maybe it's because you missed something in messaging framework setup?

I'm trying in android. I cross checked the setup also, it looks fine. Can you please tell me if it works on Android for you ?

**Comment by anikhechoyantumo** [comment]
@ThabrezAhmed No, it's still not working on Android. I am trying to implement it by specifying my custom opening activity from AndroidManifest. Will provide more information after successful implementation.

**Comment by anikhechoyantumo** [comment]
Here is my workaround for Android.

First, I have updated the channel importance from `IMPORTANCE_DEFAULT `to `IMPORTANCE_HIGH `in `ReactNativeNotificationsHandler`. That allows the system to always show the banner so I am only handling the notification tap and not the showing part.

Next, in my `MainActivity.java` I am getting the Intent in `onCreate`method that is created on banner tap. This allows to identify the tap when **app was closed**. Also, implementing the `getLaunchOptions` method of `ReactActivityDelegate` to pass the notification payload to my React Native Components as `screenProps`.

To handle the case when app is opened, I use `onNewIntent` method and trigger React Native event so i can handle it from my React Native code. 

Find my MainActivity.java file content attached.
[MainActivity.txt](https://github.com/CatalystCode/react-native-azurenotificationhub/files/4071473/MainActivity.txt)

To access notification data write `<AppContainer screenProps={this.props} />` while rendering `AppContainer` in `App.js`. Next, you can use the `this.props.screenProps` in your Components.

**Comment by phongcao** [comment]
@anikhechoyantumo For Android, can you try #94? Can you use the combination of `foreground`, `userInteraction` and `coldstart` fields to figure out all scenarios?

**Comment by phongcao** [comment]
Feel free to re-open if the master version doesn't resolve this issue.

**Comment by BrenoGO** [comment]
So, the solution in IOS is installing the react-native-firebase? I guess the coldstart is just for Android, so what is the official solution to ios?

**Comment by BrenoGO** [comment]
In IOS my solution when the app is in kill mode was using the getInitialNotification().

```
import NotificationHubIos from 'react-native-azurenotificationhub/index.ios';
NotificationHubIos.getInitialNotification()
        .then(notification => {
          logger(`MOBILE: initial notification:${JSON.stringify(notification)}`);
        })
        .catch(err => logger(`MOBILE: Error in initial notification:${JSON.stringify(err)}`));
```
