### ISSUE TITLE
Error package android.support.v4.content does not exist

### ISSUE THREAD

**Issue by mohammadalijf** [CatalystCode/react-native-azurenotificationhub#75]
I have recently migrated my app to react-native 0.61.2 and i am getting the following error when i try to compile the app for release

```
error: package android.support.v4.content does not exist
import android.support.v4.content.LocalBroadcastManager;
```

**Comment by mohammadalijf** [comment]
used [jetifier](https://github.com/mikehardy/jetifier) to fix my problem

**Comment by phongcao** [comment]
Thanks for sharing!
