### ISSUE TITLE
TypeError: this._nativeModule.addListener is not a function

### ISSUE THREAD

**Issue by gcsawargi** [CatalystCode/react-native-azurenotificationhub#78]
I am getting this error in iOS. Android compilation is just fine and I am able to register the device with Azure Push Notification Hub. Any idea why this is?

TypeError: this._nativeModule.addListener is not a function
![Simulator Screen Shot - iPhone X - 2019-12-23 at 11 23 10](https://user-images.githubusercontent.com/105079/71342623-bddd7f80-2576-11ea-8582-c7bb632b813e.png)

This error is located at:
    in App (at renderApplication.js:40)
    in RCTView (at View.js:35)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:35)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:39)

NativeEventEmitter.addListener
    NativeEventEmitter.js:47:25
new App
    App.js:77:28
<unknown>
    createClassProxy.js:98:23
instantiate
    createClassProxy.js:96:6
new App
    createClassProxy.js:112:21

**Comment by anikhechoyantumo** [comment]
Use NativeEventEmitter for Android only. On iOS add listeners to notification hub instance.

`let notificationHub = require("react-native-azurenotificationhub/index.ios");`
`notificationHub.addEventListener("register", this._onRegistered);`

**Comment by phongcao** [comment]
Thanks @anikhechoyantumo!
