### ISSUE TITLE
Notification click listener for android

### ISSUE THREAD

**Issue by ThabrezAhmed** [CatalystCode/react-native-azurenotificationhub#79]
I tried this package and it works like charm for react native Android. 
I just want to know, Is there any event listener to track notification click.

Can anyone help me on this. Thanks in advance for your time.

**Comment by anikhechoyantumo** [comment]
We are currently discussing solutions here:
https://github.com/CatalystCode/react-native-azurenotificationhub/issues/73

**Comment by phongcao** [comment]
Let's use #73 to continue our discussion.
