### ISSUE TITLE
Remote notification listener not firing on iOS

### ISSUE THREAD

**Issue by ariboren** [CatalystCode/react-native-azurenotificationhub#80]
I've carefully followed the installation instructions and have `AppDelegate.m` configured as required. I'm able to successfully register and receive notifications, and `getInitialNotification` works as expected. However, callbacks bound to `NotificationHub.addEventListener('notification', callback)` never fire. Anyone else experiencing a similar issue?

**Comment by donysukardi** [comment]
I'm experiencing the same issue. And there's no notification fired when the app is on foreground either.

**Comment by jbenzshawel** [comment]
I suspect this might be due to a conflict between the Azure Notification Hub environment and your publish profile. If you are using an "App Store" iOS profile you need to use the connection string for production Azure Notification Hubs. See this comment on stackoverflow for more information: https://stackoverflow.com/questions/40532965/azure-notification-hub-and-apple-apns-push-notifications-unregistering-devices#comment68471722_40549165

The connection string for iOS and Azure Notification Hubs also needs the Listen and Send permissions from my testing. When using a connection string with just Listen permissions the registration with Azure Notification Hubs was returning a 401. 

I think this issue can be closed though. When configured correctly the remote notification listener is working with iOS

**Comment by ariboren** [comment]
Thanks @jbenzshawel. Not sure this is exactly the issue, though. My Azure Hub is configured for production. I'm using the Listen permission in the iOS client app, and the Listen, Manage, Send permission in my .NET server that handles dispatching the notifications to the Hub. Almost everything is working perfectly - users can register, test notifications go through, actual production notifications go through, and as I mentioned initially the `getInitialNotification` call is working as expected. I'm only having issues with the `notification` listener.

I may be misunderstanding your comment, but just want to be clear that this is currently functioning as expected in production with that one exception. I also have a separate hub set up and configured for development which also experiences the same issue.

**Comment by jbenzshawel** [comment]
@ariboren I agree. After I commented I reread your post and realized your issue was a little different so I removed my reply. I am able to receive notifications through the notification listener though. 

Are you sending notifications through tags?

**Comment by ariboren** [comment]
Cool, got it. Yeah, I'm using tags to send notifications to individual users.

**Comment by jbenzshawel** [comment]
Is the event firing in the simulator when testing with this library?

https://github.com/acoomans/SimulatorRemoteNotifications

**Comment by phongcao** [comment]
@ariboren @donysukardi I couldn't reproduce this issue (testing with XCode 11 & iOS 9). Can you try the latest master version and let me know if it still occurs?

**Comment by phongcao** [comment]
Please re-open and provide more details if it's still not working for you.

**Comment by ariboren** [comment]
@phongcao thanks for the reply. Updated to the latest version. I think I may not have been clear in my original post. The listener does fire if the notification is received while the app is in the foreground. And if the app is closed and opened from a notification, `getInitialNotification` does work. However, the `notification` listener doesn't fire when the a notification is received _while the app is in the background_. Should this work, or am I misunderstanding something?

(And thanks for the suggestion, @jbenzshawel. Haven't had a chance to test that yet.)

**Comment by ariboren** [comment]
I think I resolved it by adding this condition in `AppDelegate.m`:

```obj-c
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)notification
{
  // Add this check
  if (application.applicationState == UIApplicationStateInactive || application.applicationState == UIApplicationStateBackground)
  {
      [RCTAzureNotificationHubManager didReceiveRemoteNotification:notification];
  }
}
```

Now the `notification` event fires when the app was opened from a notification received while in the background, which was what I needed. Combined with `getInitialNotification` I can now handle both "reopens" and "launches" from particular notifications. You can probably close this issue now!

**Comment by phongcao** [comment]
@ariboren Thanks for sharing your solution!

**Comment by rohitadvani14** [comment]
@jbenzshawel I am facing this problem, I am using tags for sending notifications. 
Remote notification listener is getting fired when app is in the background and I open the app from the notification bar but it not firing in the cases - 
1) When the app is in foreground.
2) When the app is killed, I am receiving the push but clicking on the notification does not fires remote notification listener.
I have added all the things as documented.

**Comment by rohitadvani14** [comment]
Ok I got it.
1) Foreground notifications worked by adding local notification listener.
2) To solve the second issue, touching the notification does not fires on notification listener when the app is in killed state. I added the following code in didFinishLaunchingWithOptions method

 if ([launchOptions objectForKey:UIApplicationLaunchOptionsRemoteNotificationKey]) {
            NSDictionary *notification = [launchOptions objectForKey:UIApplicationLaunchOptionsRemoteNotificationKey];
            if (notification) {
                //logs the notification's payload
           
  [RCTAzureNotificationHubManager didReceiveRemoteNotification:notification

                                            fetchCompletionHandler:nil];


                NSLog(@"app recieved notification from remote%@",notification);
            } else {
                NSLog(@"app did not recieve notification");
            }
      }

**Comment by rlsbelmiro** [comment]
Hi guys.
I have same issue.
The remote notification did not work in IOS.

First, happened error about supportedEvents refer "remoteNotificationReceived"
I tried update line 25 in file "AzureNotificationHUBIOS.js"
The register is work, but this notification did'nt work

Can help-me??
