### ISSUE TITLE
Issue with iOS registration (404: Url request failed) 

### ISSUE THREAD

**Issue by kumarparth380** [CatalystCode/react-native-azurenotificationhub#81]
I am getting issue of `Failed To Register For Azure Notification Hub` when calling register function. I am successfully getting device token from request permission function but it throws `Error (404): URL Request Failed for <NSMutableURLRequest:xxxx>` when registering with the connectionString, hubName, senderId and tags.

Is there any issue in creating the notification hub on azure portal? But its working fine on Android end.

Also the API version is specified as 2013-04. 

Environment:-
React- 16.6.3
React-native- 0.58.5
react-native-azurenotificationhub- 0.7.0
node- 11.12.0
npm- 6.7.0

**Comment by soothran** [comment]
I'm also having this issue.

**Comment by kumarparth380** [comment]
@soothran I was using a wrong `Hub name`. Like I was using `Spect-React-Native/React-Native-Notification-Hub` but later I came to know that I just need to use `React-Native-Notification-Hub`.
So you need to have these:

```
const connectionString = '...'; // The Notification Hub connection string
const hubName = '...';          // The Notification Hub name(This is what I was getting wrong)
const senderID = '...';         // The Sender ID from the Cloud Messaging tab of the Firebase 
const tags = [ ... ];           // The set of tags to subscribe to. This can be empty also
```
