### ISSUE TITLE
Can not unregister

### ISSUE THREAD

**Issue by sp0033212000** [CatalystCode/react-native-azurenotificationhub#91]
When I click the unregister button, the promise return waning: "Connecting string cannot be null"

**Comment by phongcao** [comment]
@sp0033212000 Does it happen on iOS or Android?

**Comment by jbenzshawel** [comment]
@phongcao I am able to replicate this issue on Android

**Comment by sp0033212000** [comment]
> @sp0033212000 Does it happen on iOS or Android?

ios platform

**Comment by phongcao** [comment]
That warning is provided on purpose. You can't unregister without registering using a valid connection string first.
